; ==========================================================================
;   ENDÜSTRİYEL TERAZİ SİMÜLATÖRÜ CONFIGURATION FILE (INI)
; ==========================================================================
[Scale]
; Bağlantı kurulacak yerel IP
IP=127.0.0.1

; TCP Soket Dinleme Portu
Port=1001

; Başlangıçta simüle edilecek ağırlık
InitialWeight=0

; Başlangıç kararlılık durumu (True = Dengede, False = Sarsıntılı/US)
IsStable=True

; Terazinin maksimum ölçüm kapasitesi (Overload eşiği)
MaxCapacity=30.0

; Terazinin hassasiyeti / taksimatı (Örn: 0.001 = 1g, 0.002 = 2g, 0.005 = 5g, 0.01 = 10g)
Division=0.01

; Aktif Haberleşme Protokolü (CAS veya TOLEDO)
Protocol=CAS